#!/bin/bash

# Given an array consisting of elements Name:Value
# Displays a numbered list of Names
# Prompts for Selection
# And saves selected number and corresponding Value respectively to variables
#   with given names or to MENU_SEL and MENU_VAL
menu() {
  local -a options=("${!1}")
  local out_sel=${2:-MENU_SEL}
  local out_val=${3:-MENU_VAL}
  local sel read_opt idx=1

  for opt in "${options[@]}" ; do
    echo "$idx: ${opt#*:}"
    let idx++
  done

  if [[ ${#options[@]} -lt 10 ]] ; then
    read_opt="-N1"
  fi

  read $read_opt -p "Selection: " sel
  echo
  if [[ $sel -lt 1 ]] || [[ $sel -gt ${#options[@]} ]] ; then
    return 1
  fi

  eval $out_sel=$sel
  eval $out_val="${options[$((sel-1))]#*:}"
}

#tab=("a:AA" "b:BB" "c:CC" "d:DD" "e:EE" "f:FF" "g:GG" "h:HH" "i:II" "j:JJ" "k:KK" "l:LL")
#menu tab[@] sel_opt
#echo $?
#echo $sel_opt
#echo $MENU_VAL
