#!/bin/bash

if ! which dialog >/dev/null ; then
  echo "No dialog available"
  exit 1
fi

HEIGHT=$(($(tput lines)-6))
WIDTH=$(($(tput cols)-20))
TITLE="git-review: $@"
SELECT=1

DIFFPARAMS="-M85%"

cd $(git rev-parse --show-toplevel)

while true; do
  FILES=()
  LABELS=()
  while IFS= read -r line ; do
    FILES+=( "$line" )
    LABELS+=( "$(git diff $DIFFPARAMS --stat --stat-width=300 $@ -- $line | head -1 | cut -f1 -d'|' | sed 's/^ *//;s/ *$//')" )
  done < <(git diff $DIFFPARAMS --name-status $@ | cut -f2-)

  if [[ ${#FILES[@]} -eq 0 ]] ; then
    echo "No files to review"
    exit 0
  fi

  OPTIONS=()
  IDX=1
  for f in "${LABELS[@]}" ; do
    OPTIONS+=( "$IDX" "$f")
    let IDX++
  done

  exec 3>&1
  SELECT=$(dialog --default-item $SELECT --ok-label Review --cancel-label Exit --menu "$TITLE" $HEIGHT $WIDTH $HEIGHT "${OPTIONS[@]}" 2>&1 1>&3)
  EXITCODE=$?
  exec 3>&-

  if [[ $EXITCODE -ne 0 ]] ; then
    exit 0
  fi

  git difftool --no-prompt --tool=vimdiff $DIFFPARAMS $@ -- ${FILES[$((SELECT-1))]}
done
