#!/bin/bash

COUNT=$1
COMMAND=${*:2}
echo "retry command: $COMMAND"

for i in $(seq 1 $COUNT);
do
   echo "Attempt $i"
   eval $COMMAND
   if [ $? -eq 0 ]
   then
      echo "Success"
      exit 0
   fi
done

exit 1
